(require 'auto-complete)
(global-auto-complete-mode t)
(add-to-list 'ac-dictionary-directories "~/env/emacs/auto-complete/dict")
(require 'auto-complete-config)
(ac-config-default)

;; (ac-set-trigger-key "TAB")
(setq ac-auto-start t)
;; (setq ac-dwim t)

(define-key ac-completing-map "\ESC" 'ac-stop)
;; (when (require 'auto-complete nil t)
;;   (require 'auto-complete-yasnippet)
;;   (require 'auto-complete-python)
;;   (require 'auto-complete-css) 
;;   (require 'auto-complete-cpp)  
;;   (require 'auto-complete-emacs-lisp)  
;;   (require 'auto-complete-semantic)  
;;   (require 'auto-complete-gtags)

;;   (global-auto-complete-mode t)
;;   (setq ac-auto-start 3)
;;   (setq ac-dwim t)
;;   (set-default 'ac-sources '(ac-source-yasnippet ac-source-abbrev ac-source-words-in-buffer ac-source-files-in-current-dir ac-source-symbols))
;; )
